### ISSUE TITLE
[Feature Request] Flycheck support

### ISSUE THREAD

**Issue by jeremysalwen** [philippe-grenet/exordium#101]
Is there a reason why Flymake is used instead of Flycheck?  My experience with Flycheck has been better.  How hard would it be for me to replace Flymake with Flycheck for my Exordium setup?

**Comment by philippe-grenet** [comment]
Don't know. If you think Flycheck is a better choice, make it work for you and send me a PR.

By the way, do you work at Bloomberg ? I and a lot of people who use Exordium do. Just curious.

**Comment by jeremysalwen** [comment]
Ok, I'll take a look.  I don't work at Bloomberg, I just found Exordium while googling for an rtags based Emacs setup.

**Comment by philippe-grenet** [comment]
Closing this since this has been done (a year ago!)
