### ISSUE TITLE
Makes an invalid assumption that the scroll-bar library is loaded

### ISSUE THREAD

**Issue by phil-s** [philippe-grenet/exordium#119]
Refer to https://www.reddit.com/r/emacs/comments/8tmyff/scrollbarmode_missing/

**Comment by philippe-grenet** [comment]
I'm still on Emacs 25 on OS X, will check when I get a chance. Meanwhile someone gave you a couple of workarounds in Reddit that should work. Thanks for using Exordium!

**Comment by phil-s** [comment]
Cheers.  It wasn't actually my post on reddit, but that person didn't seem to have followed up here.

**Comment by philippe-grenet** [comment]
Ok I think the issue is fixed now. Could you try when you get a chance?

**Comment by phil-s** [comment]
I can't test it myself, as I neither use OSX nor a GUI-less version of Emacs; however the code change looks good to me, FWIW.  The only other thing I might suggest is an accompanying code comment to explain why it is that `set-scroll-bar-mode` might not be bound.
