### ISSUE TITLE
cpp/h switching with C-TAB not working

### ISSUE THREAD

**Issue by Seanmatthews** [philippe-grenet/exordium#122]
Are there any special requirements for getting this to work? I created a simple test class header and implementation with just a constructor. Both files, test.cpp and test.h, live in the same directory. C-TAB does not produce an effect.

**Comment by philippe-grenet** [comment]
It should work out of the box. I just did the same thing as you did, and I am able to switch between the header and the cpp buffers with `C-tab`. It works as long as the files have the same name (without the extension).

Make sure that Emacs opens these file in C++ mode (mode bar should display `C++/l`). And while in either `test.h` or `test.cpp`, check what the C-tab key is bound to: you can type `C-h k C-tab`. It should display this:

```
<C-tab> runs the command cpp-switch-h-cpp (found in c++-mode-map), which is an
interactive Lisp function in ‘init-cpp.el’.

It is bound to <C-tab>.

(cpp-switch-h-cpp ARG)

Switch between .h and .cpp buffer or file. Look first into the
 open buffers, and look into the current directory if no matching
 buffer was found.
 With argument, switch to the second choice. For example, from a
 .h or a .cpp open the .t.cpp, or from a .t.cpp open the .cpp.
```

If it does not, it means that something is rebinding `C-tab` to something else. Let me know.

**Comment by philippe-grenet** [comment]
Closing. Please reopen if you are still stuck.
