### ISSUE TITLE
Enhance function alignment to fix `&` and `*` alignment

### ISSUE THREAD

**Issue by edbaunton** [philippe-grenet/exordium#36]
A common mistake is to write:

    void foo(const MyObj & obj,
                  SomeObj *       ptr);

which should of course be:

    void foo(const MyObj& obj,
             SomeObj     *ptr);

(Paying attention to the association of the `&` with the type and the `*` with the value.)
It would be useful if `bde-align-functions-arguments` took account of this.

**Comment by edbaunton** [comment]
Ah this actually seems to work for `*` but possibly by accident.

**Comment by philippe-grenet** [comment]
Hmm that's weird, I've been using this function every day and I have noticed the bug about the &. I'll fix it. Note that it also doesn't play well with template arguments. Thanks.

**Comment by philippe-grenet** [comment]
I think it is fixed now. Give it a try when you get a chance.

**Comment by philippe-grenet** [comment]
Closing this. Please reopen if I missed something.
