### ISSUE TITLE
BDE style formatter functions replace the copy-paste buffer

### ISSUE THREAD

**Issue by jbibollet** [philippe-grenet/exordium#38]
When using the BDE style formatter functions, the content of the copy-paste buffer is replaced by the section of text being styled.  
Can it use another independent temporary buffer instead and leave the copy-paste untouched ?

**Comment by philippe-grenet** [comment]
This has been bothering me as well. I'll get it fixed this weekend.

**Comment by philippe-grenet** [comment]
I think I fixed it with commit c0b017aaa41e2bda9f8d18829c1e92729bd305f0 . The problem was with C-c a (align function arguments) and C-c m (align class members).

Please reopen if it still does not work.
