### ISSUE TITLE
Error with FCI

### ISSUE THREAD

**Issue by jbibollet** [philippe-grenet/exordium#41]
Not sure how to reproduce it, seems to be related with opening empty files. or emacs with no files 

Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  #[(range) "@	X\205 	AW\207" [range posn] 2]((7972 . 10335))
  mapcar(#[(range) "@	X\205 	AW\207" [range posn] 2] ((7972 . 10335) (1 . 4826) (1 . 344) (4983 . 9987) (1 . 4826)))
  fci-delete-unneeded()
  fci-update-window-for-scroll(#<window 87 on *Messages*> 7972)
  redisplay_internal\ \(C\ function\)()

**Comment by philippe-grenet** [comment]
Is this still a problem? Or should I withdraw/CNR?

**Comment by jbibollet** [comment]
havent have it for a while, so I'm going to close it.
