### ISSUE TITLE
readme gives incorrect rdm args example

### ISSUE THREAD

**Issue by jeremysalwen** [philippe-grenet/exordium#99]
the example in the readme has 

`(setq exordium-rtags-rdm-args "--isystem /opt/bb/lib64/clang/3.6.2/incluce -DBAS_NOBBENV")`

Which is incorrect, according to the elisp source, the value should be a list of strings, not a space separated string.

**Comment by jeremysalwen** [comment]
It also seems like the exordium-rtags-rdm-args option is broken in general.  line 234 of init-rtags.el passes the exordium-rtags-rdm-args as the first argument, rather than expanding it to a list of arguments. (Should be `apply` ?)

**Comment by philippe-grenet** [comment]
Thanks, I will take a look at it this weekend. I actually don't use this feature anymore. If you need to pass options to rdm, you can also create a file `~/.rdmrc`.

**Comment by jeremysalwen** [comment]
Thanks, I wrote https://github.com/philippe-grenet/exordium/pull/100 which fixes it for me.  First time writing elisp code, so make sure to double check it before merging :D
